apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-kube-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      run: argocd-kube
  template:
    metadata:
      labels:
        run: argocd-kube
    spec:
      containers:
      - image: 992382397817.dkr.ecr.ap-northeast-2.amazonaws.com/tta-website:8c88e0e
        name: argocd-kube